### ISSUE TITLE
Memory overload involving Spooner Mode is caused by previews

### ISSUE THREAD

**Issue by ThatRealSpicyDragon** [itsjustcurtis/MenyooSP#272]
Don't know if you're aware, but the commonly mentioned LOD degradation caused by the game's memory overloading that happens when using Spooner Mode is due to previews.

The glitch does not happen with previews disabled, which could hopefully be a lead to solving the issue.

Maybe items previewed aren't properly deloaded which is why it overloads the memory?

**Comment by itsjustcurtis** [comment]
That's an interesting find. The issue can be reliably fixed by turning the previews off?

**Comment by ThatRealSpicyDragon** [comment]
Completely fixed. I've never had to worry about it for months since I turned off previews.

**Comment by itsjustcurtis** [comment]
Good to know, I'll see if there is something keeping them loaded like you say, or if I can temporarily turn them off when the menu isn't open. Can you please check if turning them off _after_ having them on during a playthrough also fixes it, or does the game need to be restarted?

**Comment by ThatRealSpicyDragon** [comment]
Just tested and yes, the game needs to be restarted, turning off previews does nothing.

However, in my testing I _think_ that peds are the root, or at the very least the worst offender.
I was spam placing and scrolling through objects, vehicles, and peds and _I must stress his could just be a coincidence_ but I noticed the error got worse the most with peds.

I still don't think it's only peds that cause it, but it could be worth looking into.

**Comment by itsjustcurtis** [comment]
that annoying. so its not like I can just fix it by temporarily disabling previews whilst they're not in use. They may need to be purged from memory every time which I'm not even sure how I'd approach at this point.

**Comment by lucienlmy** [comment]
This is a limitation of the game, because when you preview it, it is equivalent to generating characters, and generating too many characters will cause memory overload

**Comment by ThatRealSpicyDragon** [comment]
So the answer is to disable previews for peds?

**Comment by itsjustcurtis** [comment]
ohhhh this is the spooner mode previews? I was thinking the image previews. That makes so much more sense as the entities are probably not being unloaded from memory properly
